[build]
command = "npm run build"
# functions = "packages/server/dist"
publish = "build"

[build.environment]
NPM_FLAGS = "--prefix=/"

[[redirects]]
force = false
from = "/*"
status = 200
to = "/index.html"
