[build]
command = "yarn build"
functions = "dist"
publish = "dist/client"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/index"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
